[package]
name = "trezor-rust"
version = "0.1.0"
authors = ["Jan Pochyla <jpochyla@gmail.com>"]

[dependencies]
r0 = "0.2.0"

[dependencies.compiler-builtins-snapshot]
features = ["memcpy"]
version = "0.0.20161008"
